# Generated by Django 5.1.4 on 2024-12-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLstore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_url', models.CharField(max_length=255, unique=True)),
                ('original_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('click_count', models.IntegerField(default=0)),
            ],
        ),
    ]
