# Generated by Django 5.1.4 on 2024-12-18 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlstore',
            name='expired_at',
        ),
    ]
